# Algorithm
algorithm: fedavg_kd

# Hyperparameters
lambda_: 0.5
T: 2.0
tau: 0.9

# Dataset
dataset_name: CIFAR-10
batch_size: 64
model_name: cifar_cnn
num_clients: 1
non_iid: false
seed: 42

# Training parameters
epochs: 10
learning_rate: 0.01
