# Algorithm
#   fedavg: baseline Federated Averaging
#   fedavg_kd: Federated Averaging with knowledge distillation
algorithm: fedavg_kd

# Hyperparameters
lambda_: 0.5
T: 2.0
tau: 0.9

# Dataset
dataset_name: CIFAR-10
batch_size: 64
model_name: cifar_cnn
num_clients: 1
non_iid: false
seed: 42

# Training parameters
epochs: 10
learning_rate: 0.01
local_epochs: 20          # number of local training passes per client
client_fraction: 0.1     # fraction C of clients sampled each round
